# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  build:
    docker:
      - image: circleci/node:9.7.1
        environment:
        - NODE_ENV: test
        - DB_USER: root
        - DB_PASS: test
        - DB_HOST: 127.0.0.1
        - DB_NAME: circle-test

      - image: circleci/postgres:10.3-alpine
        environment:
          - POSTGRES_USER: root
          - POSTGRES_PASS: test
          - POSTGRES_DB: circle-test

      - image: redis

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Postgres Client
          command: sudo apt install postgresql-client

      - run:
          name: Install global packages
          command: sudo npm install -g truffle codecov greenkeeper-lockfile@1

      - run:
          name: Greenkeeper Lockfile
          command: greenkeeper-lockfile-update

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Javascript Linter
          command: npm run lint

      - run:
          name: All Unit Tests with Code Coverage
          command: npm run test:unit:cov

      - run:
          name: Database Tests
          command: npm run test:db

      - run:
          name: Server Tests
          command: npm run test:server

      - run:
          name: Push any lockfile changes
          command: greenkeeper-lockfile-upload

      - run:
          name: Send reports to codecov.io
          command: codecov
